//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroPack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.DetailsCmds = new HashSet<DetailsCmd>();
        }
    
        public int Id { get; set; }
        public int client_id { get; set; }
        public int prop_id { get; set; }
        public int prod_id { get; set; }
        public string libelle { get; set; }
        public System.DateTime dateCommande { get; set; }
        public bool validite { get; set; }
        public string statut { get; set; }
    
        public virtual Agriculteur Agriculteur { get; set; }
        public virtual Client Client { get; set; }
        public virtual Produit Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsCmd> DetailsCmds { get; set; }
    }
}
