//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroPack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panier
    {
        public int id { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idProduit { get; set; }
        public string Statut { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
