//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroPack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Commandes = new HashSet<Commande>();
            this.DetailsCmds = new HashSet<DetailsCmd>();
        }
    
        public int @ref { get; set; }
        public Nullable<int> prop_id { get; set; }
        public string nom { get; set; }
        public string categorie { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<decimal> prix { get; set; }
        public int refChamps { get; set; }
    
        public virtual Champ Champ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsCmd> DetailsCmds { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
